Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> Tim this can finally be merged.  I can post recheck here but that does not run sonar.  After merge, post "run-sonar" on this change.

Did that but merge-master Jenkins failed:
HTTPError: 400 Client Error: File already exists. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/
It seems to me that it tries to make a test pypi publishing with existing sdppy version and it fails, I think pom.xml file change should not trigger pypi testing at all but is this now change because pom.xml file is under ricsdl-package directory?

Patch-set: 4